name: super_editor_quill
description: "Quill extensions for Super Editor"
version: 0.0.1-dev.1
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  super_editor: ^0.3.0-dev.1
  logging: ^1.0.1
  dart_quill_delta: ^9.4.1
  collection: ^1.18.0
  super_editor_alignable_list_item:
    path: ../super_editor_alignable_list_item

dependency_overrides:
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor

  attributed_text:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: attributed_text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  text_table: ^4.0.3

flutter:
